# Generated by Django 3.0.6 on 2021-03-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apicase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='case名称', max_length=64, verbose_name='case名称')),
                ('method', models.CharField(max_length=64, verbose_name='请求方式')),
                ('headers', models.CharField(max_length=1000, null=True, verbose_name='headers')),
                ('body', models.CharField(max_length=5000, null=True, verbose_name='body')),
                ('expected', models.CharField(max_length=100, verbose_name='预期结果')),
                ('actual', models.CharField(max_length=100, verbose_name='实际结果')),
                ('module_id', models.PositiveIntegerField(max_length=11, verbose_name='所属模块id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apicase',
            },
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('step', models.CharField(max_length=1000, verbose_name='操作步骤')),
                ('result', models.CharField(max_length=1000, verbose_name='预期结果')),
                ('grade', models.CharField(max_length=100, verbose_name='用例等级')),
                ('execution', models.CharField(max_length=100, verbose_name='执行状态')),
                ('cover', models.CharField(max_length=100, verbose_name='覆盖状态')),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模块名')),
                ('file_name', models.CharField(max_length=64, verbose_name='json文件名')),
                ('project_id', models.PositiveSmallIntegerField(max_length=11, verbose_name='项目ID')),
            ],
            options={
                'db_table': 'module',
            },
        ),
    ]
